### ISSUE TITLE
写入elasticsearch 8.2.2提示这个

### ISSUE THREAD

**Issue by damuzhi** [kevwan/go-stash#16]
{"@timestamp":"2022-06-09T17:33:05.261+08:00","level":"error","content":"writer.go:60 elastic: Error 400 (Bad Request): Action/metadata line [1] contains an unknown parameter [_type] [type=illegal_argument_exception]"}

**Comment by Zhang21** [comment]
代码用的es库是v7的，只支持7.x。

```
github.com/olivere/elastic/v7 v7.0.32
```

**Comment by mfuuzy** [comment]
我也遇到了这个问题，我注意到有个作者提了PR说是支持 8.x，我试了下他的代码还是报这个错误

**Comment by wzlove** [comment]
因为8.x去掉了 _type 字段，所以只需要将writer.go中的 以下代码删除即可
`if len(w.docType) > 0 {
      req = req.Type(w.docType)
}`

**Comment by kevwan** [comment]
> 因为8.x去掉了 _type 字段，所以只需要将writer.go中的 以下代码删除即可 `if len(w.docType) > 0 { req = req.Type(w.docType) }`

Submit a PR? Thanks!

**Comment by wzlove** [comment]
> > 因为8.x去掉了 _type 字段，所以只需要将writer.go中的 以下代码删除即可 `if len(w.docType) > 0 { req = req.Type(w.docType) }`
> 
> Submit a PR? Thanks!

https://github.com/kevwan/go-stash/pull/43

**Comment by kevwan** [comment]
fixed by #43
