### ISSUE TITLE
docker image can't use

### ISSUE THREAD

**Issue by Rebellioncry** [kevwan/go-stash#9]
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

**Comment by Rebellioncry** [comment]
Does go-stash support ES 7.x ? If can't, then we will use logstash

**Comment by kevwan** [comment]
> WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested

I'll fix it. Thanks for reporting!

**Comment by kevwan** [comment]
Changed to amd64.

**Comment by Rebellioncry** [comment]
@kevwan Which versions of ES and Kafka does go-stash support?

**Comment by kevwan** [comment]
You can check it out from go.mod.

```
github.com/olivere/elastic/v7 v7.0.28
```

**Comment by Rebellioncry** [comment]
thank you
